require:
  - standard
  - standard-custom
  - standard-performance
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

inherit_gem:
  standard: config/base.yml
  standard-custom: config/base.yml
  standard-performance: config/base.yml

AllCops:
  NewCops: enable
RSpec/ExampleLength:
  CountAsOne: ['array', 'heredoc', 'method_call', 'hash']
