# #Pinwheel
#
# Pinwheel is the API for Payroll
#
# The version of the OpenAPI document: v2023-11-22
# Contact: support@getpinwheel.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.8.0
#

$:.push File.expand_path("../lib", __FILE__)
require "pinwheel/version"

Gem::Specification.new do |s|
  s.name = "pinwheel"
  s.version = Pinwheel::VERSION
  s.platform = Gem::Platform::RUBY
  s.authors = ["OpenAPI-Generator"]
  s.email = ["support@getpinwheel.com"]
  s.homepage = "https://openapi-generator.tech"
  s.summary = "A Ruby client for the [Pinwheel Payroll API](https://docs.pinwheelapi.com/public/reference/api-overview).
"
  s.description = "A Ruby client for the Pinwheel API.
Generated using [openapi-generator](https://openapi-generator.tech/) mirroring the [configuration that Plaid uses](https://github.com/plaid/plaid-openapi?tab&#x3D;readme-ov-file#plaid-ruby) to generate [their Ruby client](https://github.com/plaid/plaid-ruby).
"
  s.license = "MIT"
  s.required_ruby_version = ">= 3.0.0"
  s.metadata = {}

  s.add_runtime_dependency "faraday", ">= 1.0.1", "< 3.0"
  s.add_runtime_dependency "faraday-multipart"
  s.add_runtime_dependency "marcel"

  s.add_development_dependency "rspec", "~> 3.6", ">= 3.6.0"

  s.files = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.executables = []
  s.require_paths = ["lib"]
end
