=begin
#Pinwheel

#Pinwheel is the API for Payroll

The version of the OpenAPI document: v2023-11-22
Contact: support@getpinwheel.com
Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Pinwheel::AccountsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AccountsApi' do
  before do
    # run before each test
    @api_instance = Pinwheel::AccountsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AccountsApi' do
    it 'should create an instance of AccountsApi' do
      expect(@api_instance).to be_instance_of(Pinwheel::AccountsApi)
    end
  end

  # unit tests for disable_monitoring_v1_accounts_account_id_disable_monitoring_post
  # Disable monitoring for account
  # Disable monitoring for an account so that refresh jobs will no longer be scheduled to retrieve payroll data.
  # @param account_id UUID of the payroll account.
  # @param pinwheel_version Version identifier specifying how the Pinwheel API should behave. See the Change Management page for more information.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'disable_monitoring_v1_accounts_account_id_disable_monitoring_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for disconnect_v1_accounts_account_id_disconnect_post
  # Disconnect an account
  # Disconnect an account. This is permanent and irreversible. Once complete, an account will no longer support Earnings Streams or Recurring Access, e.g., On Demand Updates will no longer work and Monitoring will no longer be performed. However, old data will remain accessible. As mentioned above, this excludes derived data products e.g. Earnings Stream.
  # @param account_id UUID of the payroll account.
  # @param pinwheel_version Version identifier specifying how the Pinwheel API should behave. See the Change Management page for more information.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'disconnect_v1_accounts_account_id_disconnect_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_account_v1_accounts_account_id_get
  # Get Account
  # Get a single payroll account.
  # @param account_id UUID of the payroll account.
  # @param pinwheel_version Version identifier specifying how the Pinwheel API should behave. See the Change Management page for more information.
  # @param [Hash] opts the optional parameters
  # @return [GetAccountV1AccountsAccountIdGet200Response]
  describe 'get_account_v1_accounts_account_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_accounts_v1_accounts_get
  # List Accounts
  # List all payroll accounts. This is a paginated endpoint; see how Pinwheel implements pagination &lt;a href&#x3D;&#39;https://docs.pinwheelapi.com/docs/pagination-1&#39; target&#x3D;&#39;_blank&#39;&gt;here&lt;/a&gt;.
  # @param pinwheel_version Version identifier specifying how the Pinwheel API should behave. See the Change Management page for more information.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor Cursor for the page you want to retrieve.
  # @option opts [Integer] :limit The maximum number of results to return.
  # @option opts [Boolean] :connected If included, filter on connected accounts. If true, return only accounts that are connected. If false, return only accounts that are disconnected. Connected accounts are accounts for which you can retrieve new data manually using On Demand Updates or automatically via Monitoring.
  # @option opts [String] :monitoring_status Monitoring status describes the the automated ability of Pinwheel to retrieve new account information.
  # @return [GetEndUserAccountsV1EndUsersEndUserIdAccountsGet200Response]
  describe 'list_accounts_v1_accounts_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
