=begin
#Pinwheel

#Pinwheel is the API for Payroll

The version of the OpenAPI document: v2023-11-22
Contact: support@getpinwheel.com
Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Pinwheel::CompanyConnectApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CompanyConnectApi' do
  before do
    # run before each test
    @api_instance = Pinwheel::CompanyConnectApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CompanyConnectApi' do
    it 'should create an instance of CompanyConnectApi' do
      expect(@api_instance).to be_instance_of(Pinwheel::CompanyConnectApi)
    end
  end

  # unit tests for get_v1_company_connections_company_connection_id_census_get
  # List Employees
  # List all employee census data reported by the payroll platform. This is a paginated endpoint; see how Pinwheel implements pagination &lt;a href&#x3D;&#39;https://docs.pinwheelapi.com/docs/pagination-1&#39; target&#x3D;&#39;_blank&#39;&gt;here&lt;/a&gt;.
  # @param company_connection_id UUID of the Company Connection.
  # @param pinwheel_version Version identifier specifying how the Pinwheel API should behave. See the Change Management page for more information.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor Cursor for the page you want to retrieve.
  # @option opts [Integer] :limit The maximum number of results to return.
  # @return [GetV1CompanyConnectionsCompanyConnectionIdCensusGet200Response]
  describe 'get_v1_company_connections_company_connection_id_census_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_v1_company_connections_company_connection_id_employments_get
  # List Employments Data
  # List all employments data reported by the payroll platform. This is a paginated endpoint; see how Pinwheel implements pagination &lt;a href&#x3D;&#39;https://docs.pinwheelapi.com/docs/pagination-1&#39; target&#x3D;&#39;_blank&#39;&gt;here&lt;/a&gt;.
  # @param company_connection_id UUID of the Company Connection.
  # @param pinwheel_version Version identifier specifying how the Pinwheel API should behave. See the Change Management page for more information.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor Cursor for the page you want to retrieve.
  # @option opts [Integer] :limit The maximum number of results to return.
  # @return [GetV1CompanyConnectionsCompanyConnectionIdEmploymentsGet200Response]
  describe 'get_v1_company_connections_company_connection_id_employments_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_v1_company_connections_company_connection_id_get
  # Get Company Connection
  # Get Company Connection.
  # @param company_connection_id UUID of the Company Connection.
  # @param pinwheel_version Version identifier specifying how the Pinwheel API should behave. See the Change Management page for more information.
  # @param [Hash] opts the optional parameters
  # @return [PostV1CompanyConnectionsPost200Response]
  describe 'get_v1_company_connections_company_connection_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_v1_company_connections_company_connection_id_incomes_get
  # List Employee Incomes
  # List all employee income data reported by the payroll platform. This is a paginated endpoint; see how Pinwheel implements pagination &lt;a href&#x3D;&#39;https://docs.pinwheelapi.com/docs/pagination-1&#39; target&#x3D;&#39;_blank&#39;&gt;here&lt;/a&gt;.
  # @param company_connection_id UUID of the Company Connection.
  # @param pinwheel_version Version identifier specifying how the Pinwheel API should behave. See the Change Management page for more information.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor Cursor for the page you want to retrieve.
  # @option opts [Integer] :limit The maximum number of results to return.
  # @return [GetV1CompanyConnectionsCompanyConnectionIdIncomesGet200Response]
  describe 'get_v1_company_connections_company_connection_id_incomes_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_v1_company_connections_company_connection_id_paystubs_employee_external_id_get
  # List Employee Paystubs
  # List employee paystubs data reported by the payroll platform. This is a paginated endpoint; see how Pinwheel implements pagination &lt;a href&#x3D;&#39;https://docs.pinwheelapi.com/docs/pagination-1&#39; target&#x3D;&#39;_blank&#39;&gt;here&lt;/a&gt;.
  # @param company_connection_id UUID of the Company Connection.
  # @param employee_external_id Employee ID as reported by their employer.
  # @param pinwheel_version Version identifier specifying how the Pinwheel API should behave. See the Change Management page for more information.
  # @param [Hash] opts the optional parameters
  # @option opts [Date] :from_pay_date Filter for paystubs with pay dates after this date.
  # @option opts [Date] :to_pay_date Filter for paystubs with pay dates before this date.
  # @option opts [String] :cursor Cursor for the page you want to retrieve.
  # @option opts [Integer] :limit The maximum number of results to return.
  # @return [GetV1CompanyConnectionsCompanyConnectionIdPaystubsEmployeeExternalIdGet200Response]
  describe 'get_v1_company_connections_company_connection_id_paystubs_employee_external_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_v1_company_connections_company_connection_id_paystubs_employee_external_id_get_0
  # List Employee Paystubs
  # List employee paystubs data reported by the payroll platform. This is a paginated endpoint; see how Pinwheel implements pagination &lt;a href&#x3D;&#39;https://docs.pinwheelapi.com/docs/pagination-1&#39; target&#x3D;&#39;_blank&#39;&gt;here&lt;/a&gt;.
  # @param company_connection_id UUID of the Company Connection.
  # @param employee_external_id Employee ID as reported by their employer.
  # @param pinwheel_version Version identifier specifying how the Pinwheel API should behave. See the Change Management page for more information.
  # @param [Hash] opts the optional parameters
  # @option opts [Date] :from_pay_date Filter for paystubs with pay dates after this date.
  # @option opts [Date] :to_pay_date Filter for paystubs with pay dates before this date.
  # @option opts [String] :cursor Cursor for the page you want to retrieve.
  # @option opts [Integer] :limit The maximum number of results to return.
  # @return [GetV1CompanyConnectionsCompanyConnectionIdPaystubsEmployeeExternalIdGet200Response]
  describe 'get_v1_company_connections_company_connection_id_paystubs_employee_external_id_get_0 test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_v1_company_connections_get
  # List Company Connections
  # List all Company Connections. This is a paginated endpoint; see how Pinwheel implements pagination &lt;a href&#x3D;&#39;https://docs.pinwheelapi.com/docs/pagination-1&#39; target&#x3D;&#39;_blank&#39;&gt;here&lt;/a&gt;.
  # @param pinwheel_version Version identifier specifying how the Pinwheel API should behave. See the Change Management page for more information.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor Cursor for the page you want to retrieve.
  # @option opts [Integer] :limit The maximum number of results to return.
  # @return [ListV1CompanyConnectionsGet200Response]
  describe 'list_v1_company_connections_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for post_v1_company_connect_link_tokens_post
  # Create Link Token
  # Create a Company Connect link token used to launch a Link modal.
  # @param pinwheel_version Version identifier specifying how the Pinwheel API should behave. See the Change Management page for more information.
  # @param company_connect_link_token_create 
  # @param [Hash] opts the optional parameters
  # @return [PostV1CompanyConnectLinkTokensPost200Response]
  describe 'post_v1_company_connect_link_tokens_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for post_v1_company_connections_post
  # Create Company Connection
  # Create a Company Connection used to get income &amp; employment data from your target company.
  # @param pinwheel_version Version identifier specifying how the Pinwheel API should behave. See the Change Management page for more information.
  # @param company_connection_create 
  # @param [Hash] opts the optional parameters
  # @return [PostV1CompanyConnectionsPost200Response]
  describe 'post_v1_company_connections_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
