=begin
#Pinwheel

#Pinwheel is the API for Payroll

The version of the OpenAPI document: v2023-11-22
Contact: support@getpinwheel.com
Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Pinwheel::DirectDepositAllocationsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DirectDepositAllocationsApi' do
  before do
    # run before each test
    @api_instance = Pinwheel::DirectDepositAllocationsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DirectDepositAllocationsApi' do
    it 'should create an instance of DirectDepositAllocationsApi' do
      expect(@api_instance).to be_instance_of(Pinwheel::DirectDepositAllocationsApi)
    end
  end

  # unit tests for get_direct_deposit_allocations_v1_accounts_account_id_direct_deposit_allocations_get
  # Get Direct Deposit Allocations
  # The Direct Deposit Allocations endpoint returns the current direct deposit allocations configured for the specified account.
  # @param account_id UUID of the payroll account.
  # @param pinwheel_version Version identifier specifying how the Pinwheel API should behave. See the Change Management page for more information.
  # @param [Hash] opts the optional parameters
  # @return [GetDirectDepositAllocationsV1AccountsAccountIdDirectDepositAllocationsGet200Response]
  describe 'get_direct_deposit_allocations_v1_accounts_account_id_direct_deposit_allocations_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
