=begin
#Pinwheel

#Pinwheel is the API for Payroll

The version of the OpenAPI document: v2023-11-22
Contact: support@getpinwheel.com
Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Pinwheel::EmployersAndPlatformsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'EmployersAndPlatformsApi' do
  before do
    # run before each test
    @api_instance = Pinwheel::EmployersAndPlatformsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of EmployersAndPlatformsApi' do
    it 'should create an instance of EmployersAndPlatformsApi' do
      expect(@api_instance).to be_instance_of(Pinwheel::EmployersAndPlatformsApi)
    end
  end

  # unit tests for get_employer_v1_employers_employer_id_get
  # Get Employer
  # Get an Employer given the employer ID.
  # @param employer_id UUID of the employer.
  # @param pinwheel_version Version identifier specifying how the Pinwheel API should behave. See the Change Management page for more information.
  # @param [Hash] opts the optional parameters
  # @return [GetEmployerV1EmployersEmployerIdGet200Response]
  describe 'get_employer_v1_employers_employer_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_platform_v1_platforms_platform_id_get
  # Get Platform
  # Get a payroll platform supported by Link.
  # @param platform_id UUID of the platform.
  # @param pinwheel_version Version identifier specifying how the Pinwheel API should behave. See the Change Management page for more information.
  # @param [Hash] opts the optional parameters
  # @return [GetPlatformV1PlatformsPlatformIdGet200Response]
  describe 'get_platform_v1_platforms_platform_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_v1_employers_get
  # List Employers
  # List all employers supported by Link. This is a paginated endpoint; see how Pinwheel implements pagination &lt;a href&#x3D;&#39;https://docs.pinwheelapi.com/docs/pagination-1&#39; target&#x3D;&#39;_blank&#39;&gt;here&lt;/a&gt;.
  # @param pinwheel_version Version identifier specifying how the Pinwheel API should behave. See the Change Management page for more information.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor Cursor for the page you want to retrieve.
  # @option opts [Integer] :limit The maximum number of results to return.
  # @option opts [Time] :last_updated Filter for results updated more recently than &#x60;last_updated&#x60;. ISO 8601 timestamp.
  # @return [GetV1EmployersGet200Response]
  describe 'get_v1_employers_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_v1_search_get
  # Search Employers and Platforms
  # Search all employers and platforms supported by Link.
  # @param q Search query on the employer/platform name.
  # @param pinwheel_version Version identifier specifying how the Pinwheel API should behave. See the Change Management page for more information.
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :supported_jobs Filter on supported jobs. Multiple keys are allowed. May be expanded to include new enum values (see our Change Management policy).
  # @option opts [Array<String>] :response_types Filter on response type. Multiple keys are allowed. May be expanded to include new enum values (see our Change Management policy).
  # @option opts [Boolean] :amount_supported Filter on amount_supported. If true, results that support setting a specific dollar amount for direct deposit switches will be returned. If false, results that support setting a specific dollar amount for direct deposit switches will be excluded.
  # @option opts [String] :platform_type If included, filters results by the platform &#x60;type&#x60;. Platforms are either &#x60;payroll&#x60; or &#x60;time_and_attendance&#x60;. Most platforms are &#x60;payroll&#x60;. Payroll platforms support operations such as updating direct deposit allocation settings. Time &amp; Attendance platforms contain data around shifts and hours worked, but do not support payroll operations.
  # @option opts [Integer] :limit The maximum number of results to return.
  # @return [GetV1SearchGet200Response]
  describe 'get_v1_search_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_platforms_v1_platforms_get
  # List Platforms
  # List all payroll platforms supported by Link. This is a paginated endpoint; see how Pinwheel implements pagination &lt;a href&#x3D;&#39;https://docs.pinwheelapi.com/docs/pagination-1&#39; target&#x3D;&#39;_blank&#39;&gt;here&lt;/a&gt;.
  # @param pinwheel_version Version identifier specifying how the Pinwheel API should behave. See the Change Management page for more information.
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :include_esps ESP (employer-specific platform) is a term that is used to describe an Employer that uses a unique, dedicated payroll portal to serve their employees. Eg. - Walmart employees will authenticate via a Walmart payroll portal, whereas employees at Hilton will authenticate via ADP. ESPs can be thought of as both employers and platforms, so you can use this flag to include ESPs in the set of supported payroll platforms if desired.
  # @option opts [String] :type If included, filters results by the platform &#x60;type&#x60;. Platforms are either &#x60;payroll&#x60; or &#x60;time_and_attendance&#x60;. Most platforms are &#x60;payroll&#x60;. Payroll platforms support operations such as updating direct deposit allocation settings. Time &amp; Attendance platforms contain data around shifts and hours worked, but do not support payroll operations.
  # @option opts [String] :cursor Cursor for the page you want to retrieve.
  # @option opts [Integer] :limit The maximum number of results to return.
  # @option opts [Time] :last_updated Filter for results updated more recently than &#x60;last_updated&#x60;. ISO 8601 timestamp.
  # @return [ListPlatformsV1PlatformsGet200Response]
  describe 'list_platforms_v1_platforms_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
