=begin
#Pinwheel

#Pinwheel is the API for Payroll

The version of the OpenAPI document: v2023-11-22
Contact: support@getpinwheel.com
Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Pinwheel::IncomeAndEmploymentApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'IncomeAndEmploymentApi' do
  before do
    # run before each test
    @api_instance = Pinwheel::IncomeAndEmploymentApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of IncomeAndEmploymentApi' do
    it 'should create an instance of IncomeAndEmploymentApi' do
      expect(@api_instance).to be_instance_of(Pinwheel::IncomeAndEmploymentApi)
    end
  end

  # unit tests for get_employment_v1_accounts_account_id_employment_get
  # Get Employment
  # Get the current employment information of the account owner.
  # @param account_id UUID of the payroll account.
  # @param pinwheel_version Version identifier specifying how the Pinwheel API should behave. See the Change Management page for more information.
  # @param [Hash] opts the optional parameters
  # @return [GetEmploymentV1AccountsAccountIdEmploymentGet200Response]
  describe 'get_employment_v1_accounts_account_id_employment_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_identity_v1_accounts_account_id_identity_get
  # Get Identity
  # Get the current identity information of the account owner.
  # @param account_id UUID of the payroll account.
  # @param pinwheel_version Version identifier specifying how the Pinwheel API should behave. See the Change Management page for more information.
  # @param [Hash] opts the optional parameters
  # @return [GetIdentityV1AccountsAccountIdIdentityGet200Response]
  describe 'get_identity_v1_accounts_account_id_identity_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_income_v1_accounts_account_id_income_get
  # Get Income
  # Get the current income information of the account owner.
  # @param account_id UUID of the payroll account.
  # @param pinwheel_version Version identifier specifying how the Pinwheel API should behave. See the Change Management page for more information.
  # @param [Hash] opts the optional parameters
  # @return [GetIncomeV1AccountsAccountIdIncomeGet200Response]
  describe 'get_income_v1_accounts_account_id_income_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_paystub_v1_accounts_account_id_paystubs_paystub_id_get
  # Get Paystub
  # Get a single paystub.
  # @param paystub_id The id of the paystub.
  # @param account_id UUID of the payroll account.
  # @param pinwheel_version Version identifier specifying how the Pinwheel API should behave. See the Change Management page for more information.
  # @param [Hash] opts the optional parameters
  # @return [GetPaystubV1AccountsAccountIdPaystubsPaystubIdGet200Response]
  describe 'get_paystub_v1_accounts_account_id_paystubs_paystub_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_paystubs_v1_accounts_account_id_paystubs_get
  # List Paystubs
  # The paystubs endpoint allows you to query for payouts to an end user. Each paystub contains broken out and aggregated earnings information, as well as relevant dates. Paystubs are returned in reverse chronological order by &#x60;pay_date&#x60;. This is a paginated endpoint; see how Pinwheel implements pagination &lt;a href&#x3D;&#39;https://docs.pinwheelapi.com/docs/pagination-1&#39; target&#x3D;&#39;_blank&#39;&gt;here&lt;/a&gt;.
  # @param account_id UUID of the payroll account.
  # @param pinwheel_version Version identifier specifying how the Pinwheel API should behave. See the Change Management page for more information.
  # @param [Hash] opts the optional parameters
  # @option opts [Date] :from_pay_date Filter for paystubs with pay dates after this date.
  # @option opts [Date] :to_pay_date Filter for paystubs with pay dates before this date.
  # @option opts [String] :cursor Cursor for the page you want to retrieve.
  # @option opts [Integer] :limit The maximum number of results to return.
  # @return [ListPaystubsV1AccountsAccountIdPaystubsGet200Response]
  describe 'list_paystubs_v1_accounts_account_id_paystubs_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_shifts_v1_accounts_account_id_shifts_get
  # List Shifts
  # The shifts endpoint allows you to query for ongoing and completed work performed by an end user. It includes details about shift dates, timestamps, the type of work, and associated earnings. Shifts are returned in reverse chronological order by &#x60;end_date&#x60;. This is a paginated endpoint; see how Pinwheel implements pagination &lt;a href&#x3D;&#39;https://docs.pinwheelapi.com/docs/pagination-1&#39; target&#x3D;&#39;_blank&#39;&gt;here&lt;/a&gt;.
  # @param account_id UUID of the payroll account.
  # @param pinwheel_version Version identifier specifying how the Pinwheel API should behave. See the Change Management page for more information.
  # @param [Hash] opts the optional parameters
  # @option opts [Date] :from_start_date Return shifts where the &#x60;start_date&#x60; field is on or after this date. ISO 8601 format.
  # @option opts [Date] :to_start_date Return shifts where the &#x60;start_date&#x60; field is on or before this date. ISO 8601 format.
  # @option opts [Date] :from_end_date Return shifts where the &#x60;end_date&#x60; field is on or after this date. ISO 8601 format.
  # @option opts [Date] :to_end_date Return shifts where the &#x60;end_date&#x60; field is on or before this date. ISO 8601 format.
  # @option opts [Integer] :limit The maximum number of results to return.
  # @option opts [String] :cursor Cursor for the page you want to retrieve.
  # @return [ListShiftsV1AccountsAccountIdShiftsGet200Response]
  describe 'list_shifts_v1_accounts_account_id_shifts_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
