=begin
#Pinwheel

#Pinwheel is the API for Payroll

The version of the OpenAPI document: v2023-11-22
Contact: support@getpinwheel.com
Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Pinwheel::JobsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'JobsApi' do
  before do
    # run before each test
    @api_instance = Pinwheel::JobsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of JobsApi' do
    it 'should create an instance of JobsApi' do
      expect(@api_instance).to be_instance_of(Pinwheel::JobsApi)
    end
  end

  # unit tests for get_jobs_v1_jobs_get
  # List Completed Jobs
  # List all completed jobs which were initiated by Link (i.e., excluding refresh jobs for monitoring). This is a paginated endpoint; see how Pinwheel implements pagination &lt;a href&#x3D;&#39;https://docs.pinwheelapi.com/docs/pagination-1&#39; target&#x3D;&#39;_blank&#39;&gt;here&lt;/a&gt;.
  # @param pinwheel_version Version identifier specifying how the Pinwheel API should behave. See the Change Management page for more information.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :link_token_id UUID of the link token triggering the job.
  # @option opts [String] :account_id UUID of the payroll account.
  # @option opts [Array<String>] :job_types List of job types. May be expanded to include new enum values (see our Change Management policy).
  # @option opts [String] :outcome The outcome of the job.
  # @option opts [Integer] :limit The maximum number of results to return.
  # @option opts [String] :cursor Cursor for the page you want to retrieve.
  # @option opts [Time] :from_timestamp Return results after this ISO 8601 timestamp.
  # @option opts [Time] :to_timestamp Return results to this ISO 8601 timestamp.
  # @return [GetJobsV1JobsGet200Response]
  describe 'get_jobs_v1_jobs_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
