=begin
#Pinwheel

#Pinwheel is the API for Payroll

The version of the OpenAPI document: v2023-11-22
Contact: support@getpinwheel.com
Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Pinwheel::LinkTokensApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'LinkTokensApi' do
  before do
    # run before each test
    @api_instance = Pinwheel::LinkTokensApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LinkTokensApi' do
    it 'should create an instance of LinkTokensApi' do
      expect(@api_instance).to be_instance_of(Pinwheel::LinkTokensApi)
    end
  end

  # unit tests for post_v1_link_tokens_post
  # Create Link Token
  # Create a token used to launch a Link modal.
  # @param pinwheel_version Version identifier specifying how the Pinwheel API should behave. See the Change Management page for more information.
  # @param link_token_create_v20231122 
  # @param [Hash] opts the optional parameters
  # @return [PostV1LinkTokensPost200Response]
  describe 'post_v1_link_tokens_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
