=begin
#Pinwheel

#Pinwheel is the API for Payroll

The version of the OpenAPI document: v2023-11-22
Contact: support@getpinwheel.com
Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Pinwheel::WebhooksApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'WebhooksApi' do
  before do
    # run before each test
    @api_instance = Pinwheel::WebhooksApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WebhooksApi' do
    it 'should create an instance of WebhooksApi' do
      expect(@api_instance).to be_instance_of(Pinwheel::WebhooksApi)
    end
  end

  # unit tests for delete_v1_webhooks_webhook_id_delete
  # Delete Webhook
  # Delete a webhook.
  # @param webhook_id UUID of the webhook.
  # @param pinwheel_version Version identifier specifying how the Pinwheel API should behave. See the Change Management page for more information.
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'delete_v1_webhooks_webhook_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_v1_webhooks_get
  # List Webhooks
  # List all webhooks. This is a paginated endpoint; see how Pinwheel implements pagination &lt;a href&#x3D;&#39;https://docs.pinwheelapi.com/docs/pagination-1&#39; target&#x3D;&#39;_blank&#39;&gt;here&lt;/a&gt;.
  # @param pinwheel_version Version identifier specifying how the Pinwheel API should behave. See the Change Management page for more information.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor Cursor for the page you want to retrieve.
  # @option opts [Integer] :limit The maximum number of results to return.
  # @return [GetV1WebhooksGet200Response]
  describe 'get_v1_webhooks_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_webhook_by_id_v1_webhooks_webhook_id_get
  # Get Webhook
  # Get webhook by id.
  # @param webhook_id UUID of the webhook.
  # @param pinwheel_version Version identifier specifying how the Pinwheel API should behave. See the Change Management page for more information.
  # @param [Hash] opts the optional parameters
  # @return [PostV1WebhooksPost200Response]
  describe 'get_webhook_by_id_v1_webhooks_webhook_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for post_v1_webhooks_post
  # Create Webhook
  # Create a webhook to use for callbacks from Pinwheel jobs.
  # @param pinwheel_version Version identifier specifying how the Pinwheel API should behave. See the Change Management page for more information.
  # @param webhook_create_v20230418 
  # @param [Hash] opts the optional parameters
  # @return [PostV1WebhooksPost200Response]
  describe 'post_v1_webhooks_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for put_v1_webhooks_webhook_id_put
  # Update Webhook
  # Update webhook.
  # @param webhook_id UUID of the webhook.
  # @param pinwheel_version Version identifier specifying how the Pinwheel API should behave. See the Change Management page for more information.
  # @param webhook_update 
  # @param [Hash] opts the optional parameters
  # @return [PostV1WebhooksPost200Response]
  describe 'put_v1_webhooks_webhook_id_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
