=begin
#Pinwheel

#Pinwheel is the API for Payroll

The version of the OpenAPI document: v2023-11-22
Contact: support@getpinwheel.com
Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Pinwheel::CompanyConnectionCreate
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Pinwheel::CompanyConnectionCreate do
  let(:instance) { Pinwheel::CompanyConnectionCreate.new }

  describe 'test an instance of CompanyConnectionCreate' do
    it 'should create an instance of CompanyConnectionCreate' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Pinwheel::CompanyConnectionCreate)
    end
  end

  describe 'test attribute "company_name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
