=begin
#Pinwheel

#Pinwheel is the API for Payroll

The version of the OpenAPI document: v2023-11-22
Contact: support@getpinwheel.com
Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Pinwheel::EarningsStreamPayoutObjResponseV20230418
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Pinwheel::EarningsStreamPayoutObjResponseV20230418 do
  let(:instance) { Pinwheel::EarningsStreamPayoutObjResponseV20230418.new }

  describe 'test an instance of EarningsStreamPayoutObjResponseV20230418' do
    it 'should create an instance of EarningsStreamPayoutObjResponseV20230418' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Pinwheel::EarningsStreamPayoutObjResponseV20230418)
    end
  end

  describe 'test attribute "status"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["estimated", "processed"])
      # validator.allowable_values.each do |value|
      #   expect { instance.status = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "pay_date"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "net_pay"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "earnings"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
