=begin
#Pinwheel

#Pinwheel is the API for Payroll

The version of the OpenAPI document: v2023-11-22
Contact: support@getpinwheel.com
Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Pinwheel::EarningObjPublicResponseItem
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Pinwheel::EarningObjPublicResponseItem do
  let(:instance) { Pinwheel::EarningObjPublicResponseItem.new }

  describe 'test an instance of EarningObjPublicResponseItem' do
    it 'should create an instance of EarningObjPublicResponseItem' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Pinwheel::EarningObjPublicResponseItem)
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "category"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["salary", "hourly", "overtime", "double_overtime", "premium", "bonus", "commission", "tips", "vacation", "holiday", "pto", "sick", "employer_contribution", "other", "fare", "unpaid", "parental", "shift_differential", "bereavement", "life_insurance", "stock", "retirement", "medical", "meal_comp", "disability", "retro_pay"])
      # validator.allowable_values.each do |value|
      #   expect { instance.category = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "amount"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "rate"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "hours"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
