=begin
#Pinwheel

#Pinwheel is the API for Payroll

The version of the OpenAPI document: v2023-11-22
Contact: support@getpinwheel.com
Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Pinwheel::RefreshablePaginationListMeta
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Pinwheel::RefreshablePaginationListMeta do
  let(:instance) { Pinwheel::RefreshablePaginationListMeta.new }

  describe 'test an instance of RefreshablePaginationListMeta' do
    it 'should create an instance of RefreshablePaginationListMeta' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Pinwheel::RefreshablePaginationListMeta)
    end
  end

  describe 'test attribute "refreshed_at"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "count"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "next_cursor"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
