=begin
#Pinwheel

#Pinwheel is the API for Payroll

The version of the OpenAPI document: v2023-11-22
Contact: support@getpinwheel.com
Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Pinwheel::RevokeAPIKeyResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Pinwheel::RevokeAPIKeyResponse do
  let(:instance) { Pinwheel::RevokeAPIKeyResponse.new }

  describe 'test an instance of RevokeAPIKeyResponse' do
    it 'should create an instance of RevokeAPIKeyResponse' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Pinwheel::RevokeAPIKeyResponse)
    end
  end

  describe 'test attribute "data"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
