=begin
#Pinwheel

#Pinwheel is the API for Payroll

The version of the OpenAPI document: v2023-11-22
Contact: support@getpinwheel.com
Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Pinwheel::WebhookUpdate
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Pinwheel::WebhookUpdate do
  let(:instance) { Pinwheel::WebhookUpdate.new }

  describe 'test an instance of WebhookUpdate' do
    it 'should create an instance of WebhookUpdate' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Pinwheel::WebhookUpdate)
    end
  end

  describe 'test attribute "url"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "status"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["active", "paused"])
      # validator.allowable_values.each do |value|
      #   expect { instance.status = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "enabled_events"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('Array<String>', ["account.additional_connections_recommended", "company_connect.employments.added", "shifts.seven_days_synced", "verification_reports.refreshed", "paystubs.added", "income.added", "company_connect.census.added", "shifts.fully_synced", "employment.added", "shifts.thirty_days_synced", "paystubs.fully_synced", "account.monitoring_status.updated", "earnings_stream.payouts.refreshed", "shifts.ninety_days_synced", "tax_forms.added", "paystubs.thirty_days_synced", "paystubs.documents.added", "company_connect.incomes.added", "paystubs.seven_days_synced", "identity.added", "direct_deposit_switch.added", "company_connect.status.updated", "account.added", "shifts.added", "paystubs.ninety_days_synced", "direct_deposit_allocations.added"])
      # validator.allowable_values.each do |value|
      #   expect { instance.enabled_events = value }.not_to raise_error
      # end
    end
  end

end
