=begin
#Pinwheel

#Pinwheel is the API for Payroll

The version of the OpenAPI document: v2023-11-22
Contact: support@getpinwheel.com
Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'date'
require 'time'

module Pinwheel
  class IncomeAndEmploymentResponseObj
    # Name of employer, e.g., Apple, Disney, Walmart.
    attr_accessor :employer_name

    # The address of the employer.
    attr_accessor :employer_address

    # The date the employee began their job.
    attr_accessor :start_date

    # The length of time, in months, the employee has been active with the employer.
    attr_accessor :employment_duration_months

    attr_accessor :employment_status

    # The employment type e.g. full time, part time, seasonal, contractor.
    attr_accessor :employment_type

    # The date the employee was terminated.
    attr_accessor :termination_date

    # The job title of the employee.
    attr_accessor :title

    # The latest date when the employee received regular pay.
    attr_accessor :most_recent_pay_date

    # Income details for the employment.
    attr_accessor :income

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'employer_name' => :'employer_name',
        :'employer_address' => :'employer_address',
        :'start_date' => :'start_date',
        :'employment_duration_months' => :'employment_duration_months',
        :'employment_status' => :'employment_status',
        :'employment_type' => :'employment_type',
        :'termination_date' => :'termination_date',
        :'title' => :'title',
        :'most_recent_pay_date' => :'most_recent_pay_date',
        :'income' => :'income'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'employer_name' => :'String',
        :'employer_address' => :'AddressGetResponseItem',
        :'start_date' => :'Date',
        :'employment_duration_months' => :'Integer',
        :'employment_status' => :'String',
        :'employment_type' => :'String',
        :'termination_date' => :'Date',
        :'title' => :'String',
        :'most_recent_pay_date' => :'Date',
        :'income' => :'IncomeResponseObj'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Pinwheel::IncomeAndEmploymentResponseObj` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Pinwheel::IncomeAndEmploymentResponseObj`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'employer_name')
        self.employer_name = attributes[:'employer_name']
      else
        self.employer_name = nil
      end

      if attributes.key?(:'employer_address')
        self.employer_address = attributes[:'employer_address']
      end

      if attributes.key?(:'start_date')
        self.start_date = attributes[:'start_date']
      end

      if attributes.key?(:'employment_duration_months')
        self.employment_duration_months = attributes[:'employment_duration_months']
      end

      if attributes.key?(:'employment_status')
        self.employment_status = attributes[:'employment_status']
      end

      if attributes.key?(:'employment_type')
        self.employment_type = attributes[:'employment_type']
      end

      if attributes.key?(:'termination_date')
        self.termination_date = attributes[:'termination_date']
      end

      if attributes.key?(:'title')
        self.title = attributes[:'title']
      end

      if attributes.key?(:'most_recent_pay_date')
        self.most_recent_pay_date = attributes[:'most_recent_pay_date']
      end

      if attributes.key?(:'income')
        self.income = attributes[:'income']
      else
        self.income = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @employer_name.nil?
        invalid_properties.push('invalid value for "employer_name", employer_name cannot be nil.')
      end

      if @income.nil?
        invalid_properties.push('invalid value for "income", income cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @employer_name.nil?
      employment_status_validator = EnumAttributeValidator.new('String', ["employed", "terminated", "furloughed"])
      return false unless employment_status_validator.valid?(@employment_status)
      return false if @income.nil?
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] employment_status Object to be assigned
    def employment_status=(employment_status)
      validator = EnumAttributeValidator.new('String', ["employed", "terminated", "furloughed"])
      unless validator.valid?(employment_status)
        fail ArgumentError, "invalid value for \"employment_status\", must be one of #{validator.allowable_values}."
      end
      @employment_status = employment_status
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          employer_name == o.employer_name &&
          employer_address == o.employer_address &&
          start_date == o.start_date &&
          employment_duration_months == o.employment_duration_months &&
          employment_status == o.employment_status &&
          employment_type == o.employment_type &&
          termination_date == o.termination_date &&
          title == o.title &&
          most_recent_pay_date == o.most_recent_pay_date &&
          income == o.income
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [employer_name, employer_address, start_date, employment_duration_months, employment_status, employment_type, termination_date, title, most_recent_pay_date, income].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Pinwheel.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
